[telerama-musique]
title = "Les critiques disques de Télérama"
url = "https://www.telerama.fr/music/musique_dernierescritiques.php"
entrySelector = "div.t12-crilst-item"
titleSelector = "h2.t12-crilst-tit a"
linkSelector = "h2.t12-crilst-tit a"
